### ISSUE TITLE
Support multiple Android TV devices

### ISSUE THREAD

**Issue by zehnm** [unfoldedcircle/integration-androidtv#14]
At the moment only one device is supported.

This requires the "run-setup-again" functionality in the core & web-configurator, so that the configured device doesn't need to be removed first.

**Comment by ijsklont** [comment]
Is there any indication, when you might expect to be able to integrate this?

**Comment by ijsklont** [comment]
An update un this issue would be greatly appreciated

**Comment by zehnm** [comment]
Main work has been done in the [Apple TV integration](https://github.com/unfoldedcircle/integration-appletv) which can be used for this integration as well. Development for Android TV has been started. ETA: this month
