### ISSUE TITLE
HBO App Association Broken

### ISSUE THREAD

**Issue by jstrify** [unfoldedcircle/integration-androidtv#22]
### Description

Now that HBO has rebranded HBO Max to Max (and they decided not to put redirects on URLs/created a new app package), code to launch the HBO Max app will not launch the Max app.

In apps.py, I see

```
Apps = {
    "HBO Max": {"url": "https://play.hbomax.com"},
}

# Application-ID substring mappings to friendly names
# Used to show which app is currently in the foreground (currently playing)
NameMatching = {
    "hbomax": "HBO Max",
}
```

I think references should be changed to Max (or additional cross-references set up) and a new url for https://play.max.com

### How to Reproduce

1. Set up an activity with the Android TV integration. Ensure that the MAX app is installed on the device (but not HBO Max, as that app is deprecated).
2. Add the HBO Max app as a soft button on the remote.
3. When pressing the button, the Android TV device shall read "You don't have an app that can do this."

### Expected behavior

Launch of the "new" Max app (instead of the failure to launch the deprecated 

### Integration version

0.4.4

### Additional context

Apologies, I didn't feel comfortable enough making a pull request, I'm still riding around on my Github training wheels.

**Comment by zehnm** [comment]
Thanks for the info!
This seems to be the new app: https://play.google.com/store/apps/details?id=com.wbd.stream&hl=en&gl=US

I'll try to install it to test the changed app references.

**Comment by zehnm** [comment]
New information: Max is only for the US! EU still has HBO Max (and no HBO at all for Switzerland).
https://www.hbo.com/hbo-and-max
So I'll just add the new Max to the existing one...

**Comment by zehnm** [comment]
@jstrify could you please test this with the 1.6 firmware, if you can launch the new Max app?

**Comment by jstrify** [comment]
> @jstrify could you please test this with the 1.6 firmware, if you can launch the new Max app?

Worked perfectly for me. App launched when I changed the association from "HBO Max" to "Max". I think we're good to close this ticket.

**Comment by zehnm** [comment]
Thanks for the feedback, good to know it's working.
