### ISSUE TITLE
Add device profiles to map features and commands

### ISSUE THREAD

**Issue by zehnm** [unfoldedcircle/integration-androidtv#29]
### Description

While adding the new media-player features like context-menu which require a long press, I've noticed that my two Android TV streaming devices behave differently for long press actions 😏 Looks like every manufacturer does it a bit differently...
For example:
- NVIDIA Shield TV:
  - long press home: apps
  - long press back: settings
  - double click home: app switcher
- Google Chromecast:
   - long press home: settings
   - double click back: screensaver

Furthermore, the [available key-codes](https://github.com/tronikos/androidtvremote2/blob/v0.0.14/src/androidtvremote2/remotemessage.proto#L90) are highly device dependent if they work or not, from what I've gathered through user feedback.

Since the device model can be retrieved with the API, the available integration features and button mappings should be configurable and stored in device profiles. This will greatly improve user experience.

**Comment by Kat-CeDe** [comment]
Could you explain a bit more the simple commands? An example for Android TV would be perfect. I could prepare command list for Dune HD Homatics and Philips TV.

**Comment by zehnm** [comment]
I've started the feature enhancements in branch `feat/27_new-feat-cmds` where I'll probably  add the device profiles as well.
The simple commands are described in the [media-player entity](https://github.com/unfoldedcircle/core-api/blob/main/doc/entities/entity_media_player.md#simple-commands) and already used in the Apple TV integration and the aforementioned branch:
- https://github.com/unfoldedcircle/integration-appletv/blob/v0.13.4/intg-appletv/driver.py#L502-L508
- https://github.com/unfoldedcircle/integration-appletv/blob/v0.13.4/intg-appletv/driver.py#L253-L258

For Android TV it would probably make sense to somehow expose [all defined key codes](https://github.com/tronikos/androidtvremote2/blob/v0.0.14/src/androidtvremote2/remotemessage.proto#L90-L832), which then could be used in a device profile. Either with a "test mode", similar as it's already done for testing the HDMI-input keys. For example: all `KEYCODE_` prefixed commands (or their numeric value) will be sent as-is. They wouldn't even have to be defined as simple commands, and therefore wouldn't show up in the web-configurator, but could still be used in the REST API for testing.
Once the working key codes are identified, they could be put into a device profile and the driver then registers all the working keys as simple commands (which then also show up in the web-configurator).

**Comment by Kat-CeDe** [comment]
Thank you. The ATV integration is really a good example. I already used quite a lot KEYCODEs with ADB.

**Comment by zehnm** [comment]
Device profile work has been started in branch `feat/27_new-feat-cmds`.

**Comment by Kat-CeDe** [comment]
Here is something for your profiles. I wrote a program which sends the keycodes 0..400 through ADB and I watched the reaction. I did it with Philips Android TV, NVidia Shiel Pro and Dune HD Homatics. On all devices was Waipu IPTV running. Attached a list of codes and notes for important keycodes especially Philips TV as the standard input codes are not working.

Problem with these streaming devices is that all apps decide which commands they use. If I am in the mood I do the same with Kodi running.

Have fun Ralf

**Comment by zehnm** [comment]
@Kat-CeDe that's a great help, thanks! Unfortunately I don't see an attachement.
If you post the manufacturer and device names, then I can create a new profile (probably `'manufacturer': 'Philips'` with an empty model is good enough, unless it returns a different name). This information is logged during device connection, for example:
```
INFO:tv:Device information: {'manufacturer': 'Google', 'model': 'Chromecast HD', 'sw_version': '5.2.473254133'}
```

**Comment by Kat-CeDe** [comment]
I have 2019er Pro. But I will test them later on.
