### ISSUE TITLE
How to use the new profiles?

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/integration-androidtv#38]
### Description

I am trying to use profiles. I copied config/profiles to the directory where driver.json is located but I did not find any location where I can select the profile. At least for my Shield the profile is also not automatically selected. Is it already possible to add "keycode" as a digit instead of the define from androidtvremote2?

**Comment by zehnm** [comment]
See:
- https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/command_mapping.md#device-profiles
- https://github.com/unfoldedcircle/integration-androidtv/blob/main/README.md#run

No need to copy anything, define `UC_CONFIG_HOME` to the `./config` subdirectory and the profiles are loaded.
https://github.com/unfoldedcircle/integration-python-library?tab=readme-ov-file#environment-variables

```
DEBUG:profiles:Loading device profile: default.json
DEBUG:profiles:Loading device profile: Google_Chromecast.json
DEBUG:profiles:Loading device profile: NVIDIA_SHIELD.json
DEBUG:profiles:Loading device profile: Philips_AndroidTV.json
INFO:profiles:Loaded device profiles: 4
INFO:driver:[Wohnzimmer TV] Configured Android TV device xxxxxxxxxxxx with profile: NVIDIA SHIELD
INFO:driver:[Office TV] Configured Android TV device yyyyyyyyyyyy with profile: Google Chromecast
```

Profiles are auto-matched based on the returned device information. Assigning a custom profile might be added later.

**Comment by Kat-CeDe** [comment]
Hi,
profiles will be very helpful in the future. I had problems finding my manufacturer and model because you match both. For new profiles a small change in profiles.py might be helpful:
_LOG.error("Error loading device profile file manufacturer:%s model:%s", os.path.basename(file), ex)
So if you create a new profiles you really see what is manufacturer and what is model. In case of my Philips it is manufacturer TPV and model 2021/22.

A good idea might be also to support a profile selection if the device is still not supported by a profile. I think about the Sony TV which might be similar to Philips.

I created a profile for my Philips and added for instance:
  "simple_commands": [
    "CHANNEL_LIST"
  ],
  "command_map": {
    "CHANNEL_LIST": {
      "keycode": "378",
      "action": "SHORT"
    }
  }
But when I press a button I defined with CHANNEL_LIST I get:
INFO:driver:[22 Philips UHD Android TV] command: CHANNEL_LIST 
ERROR:tv:[22 Philips UHD Android TV] Cannot send command, invalid key_code: 378
This might be because androidtvremote2 is blocking that.

I hope you did not fix some points today because it was made with the former version.

Ralf

**Comment by Kat-CeDe** [comment]
I found one mistake in my profile. Instead of "keycode":"378" it must be "keycode":378 then I get 

DEBUG:ucapi.api:[('192.168.178.227', 40894)] <-: {"kind":"req","id":178,"msg":"entity_command","msg_data":{"cmd_id":"CHANNEL_LIST","entity_id":"38C804A79B23","entity_type":"media_player"}}
INFO:driver:[22 Philips UHD Android TV] command: CHANNEL_LIST 
DEBUG:androidtvremote2:Sending: remote_key_inject { key_code: 378 direction: SHORT }
DEBUG:ucapi.api:[('192.168.178.227', 40894)] ->: {"kind": "resp", "req_id": 178, "code": 200, "msg": "result", "msg_data": {}}

but sadly no the same reaction as with adb.

Ralf still searching

**Comment by zehnm** [comment]
> I had problems finding my manufacturer and model because you match both. For new profiles a small change in profiles.py might be helpful:

This change is not required, manufacturer & model name are already logged after the device is connected:
https://github.com/unfoldedcircle/integration-androidtv/blob/073d9cd14b1a95613935c5311b2e55bf031e9277/intg-androidtv/tv.py#L428-L429
```
INFO:tv:[Office TV] Device information: {'manufacturer': 'Google', 'model': 'Chromecast HD', 'sw_version': '5.2.473254133'}
```
Model matching is optional, if the field is empty (`"model": ""`) then only the manufacturer is matched: https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/command_mapping.md#device-profile-matching

**Comment by zehnm** [comment]
@Kat-CeDe are there still issues or questions about using profiles, or can this be closed?

**Comment by Kat-CeDe** [comment]
No as I already created my first 2 profiles I think I know how thes work now.

Ralf
