### ISSUE TITLE
Support input source key commands

### ISSUE THREAD

**Issue by zehnm** [unfoldedcircle/integration-androidtv#4]
With the [androidtvremot2](https://github.com/tronikos/androidtvremote2) library it is not possible to retrieve apps or physical input sources as HDMI1 etc.
This is an important feature for TV devices using Android TV, e.g. Sony.

As reported in:
- https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/128

Enhancement tasks:
- [x] test if the key commands to switch inputs work:
https://github.com/tronikos/androidtvremote2/blob/v0.0.14/src/androidtvremote2/remotemessage.proto#L681-L731
- [ ] map all input keys to sources. The current `source_list` and `source` handling has to be enhanced: 
  - use the current defined app list and a new input list.
  - use a well defined prefix for the input texts, e.g. `Input `, to distinguish an app from an input key command
  - when the user selects a new source, check if it's an app or input and call either `androidTv.launchApp` or `send_key_command`

**Comment by Kat-CeDe** [comment]
Neither for Philip TVs.

**Comment by zehnm** [comment]
This issue will be closed with PR #34.
It's unfortunate that the `KEYCODE_TV_INPUT_*` commands don't seem to work with most TV brands. With the new device profile feature they can still be used if we find a working model.

**Comment by Kat-CeDe** [comment]
I prepared a test for the input commands I will test on my Philips. Yesterday I could once switch to Sat but nothing else. So there is still hope.

**Comment by ijsklont** [comment]
This is great, as it will also offer better and easier options of remapping the 0~9 keys to other functions (like directly booting up an app) on the AndroidTV device.
