### ISSUE TITLE
Add Long-Press Menu for moving tiles

### ISSUE THREAD

**Issue by pri-me** [unfoldedcircle/integration-androidtv#41]
### Description

Android TV has a menu which pops up when "Ok" (Confirm/Enter) is long pressed (tested on Nvidia Shield, Philips Tv and Home Assistant Android Tv integration). It allows to move apps on the dashboard.
![IMG_20240414_023233](https://github.com/unfoldedcircle/integration-androidtv/assets/52279202/9b3937a0-1506-4985-930f-acf8a126527d)

**Comment by zehnm** [comment]
Already implemented in v0.5.0 (included in latest Remote Two Beta firmware).
Command:
- Shield & Chromcast devices: `context_menu`
- Other devices: `CURSOR_ENTER_LONG`

**Comment by zehnm** [comment]
Forgot to add a screenshot of the activity editor:
<img width="878" alt="image" src="https://github.com/unfoldedcircle/integration-androidtv/assets/17356629/4f6c08b9-6cdc-4893-b5b6-63142e2fcf2f">
