### ISSUE TITLE
Add digit commands

### ISSUE THREAD

**Issue by pri-me** [unfoldedcircle/integration-androidtv#42]
### Description

Please add the digits 0-9.

**Comment by zehnm** [comment]
Already implemented in v0.5.0 (included in latest Remote Two Beta firmware).
- Feature: `numpad`
- Commands: `DIGIT_0` .. `DIGIT_9`

https://github.com/unfoldedcircle/integration-androidtv/blob/main/docs/command_mapping.md

Numpad commands are exposed in an activity for the Android TV media-player entity:
<img width="450" alt="image" src="https://github.com/unfoldedcircle/integration-androidtv/assets/17356629/a31cd1a5-c158-421a-b27b-136adc29fff4">
