### ISSUE TITLE
Allow manual URL option for app launch

### ISSUE THREAD

**Issue by gespo89** [unfoldedcircle/integration-androidtv#47]
### Description

For launching apps, instead of defaulting to an error for apps not in the hard-coded map, it would be nice to additionally have the ability to specify the URL directly so advanced users can add buttons for missing apps without waiting for them to be included in a software update.

**Comment by zehnm** [comment]
That's quite easy to implement and a good addition! Implementing #50 will likely take longer.
- enhance select_source in tv.py to pass on parameter if not in mapping lists.
- change web-configurator to allow free text entry for the select-source command.

**Comment by zehnm** [comment]
Web-configurator is almost ready to enter a custom app-id and should be included in the next firmware release:
<img width="477" alt="image" src="https://github.com/unfoldedcircle/integration-androidtv/assets/17356629/f7cc0511-167c-472b-b034-7e47bbe781b3">

**Comment by zehnm** [comment]
Available in 1.7.14, including web-configurator. For now just in the beta channel, but should become a public release tomorrow.

**Comment by gespo89** [comment]
Awesome, thanks for the quick turnaround!
